# .github/FUNDING.yml
# Support MON CS DOCS and Moebius Order

github: [moebius-order]
patreon: moebiusorder
ko_fi: moebiusorder
buy_me_a_coffee: moebiusorder
custom: ['https://mcdocs.moebiusorder.com/donate']
